name: Pull Request Closed

on:
  pull_request:
    branches-ignore:
      - "live"
    types:
      - closed

jobs:
  clean_up:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get PR branch name
        id: get_pr_branch_name
        run: |
          pr_branch_name=$(jq --raw-output .pull_request.head.ref "$GITHUB_EVENT_PATH")
          echo "pr_branch_name=${pr_branch_name}" >> $GITHUB_OUTPUT
          echo $pr_branch_name

      - name: Search branch by name
        id: get_branch_id
        run: |
          branch_id=$(curl --silent \
            "https://console.neon.tech/api/v2/projects/${{ secrets.NEON_PROJECT_ID }}/branches" \
            --header "Accept: application/json" \
            --header "Content-Type: application/json" \
            --header "Authorization: Bearer ${{ secrets.NEON_API_KEY }}" \
            | jq -r .branches \
            | jq -c '.[] | select(.name | contains("'${{ steps.get_pr_branch_name.outputs.pr_branch_name }}'")) .id' \
            | jq -r \
            ) \
            
          echo "branch_id=${branch_id}" >> $GITHUB_OUTPUT

      - name: Delete Neon Branch
        uses: neondatabase/delete-branch-action@v2
        with:
          project_id: ${{ secrets.NEON_PROJECT_ID }}
          branch_id: ${{ steps.get_branch_id.outputs.branch_id }}
          api_key: ${{ secrets.NEON_API_KEY }}

      - name: Delete Preview Environment variables
        run: |
          token="${{ secrets.VERCEL_TOKEN }}"
          branch_name="${{ steps.get_pr_branch_name.outputs.pr_branch_name }}"

          # Link the project to get the project ID
          vercel link -t $token -y

          # List environment variables in JSON format and use awk to filter out non-JSON lines
          echo "Listing environment variables for preview environment and branch: $branch_name"
          environments=$(vercel env ls --environment=preview --git-branch="$branch_name" -t $token --json | awk '/^\[.*\]$/ {print}')
          echo "Environment vars to delete: $environments"

          # Check if environments variable is empty or not
          if [ -z "$environments" ]; then
            echo "No environment variables found to delete."
          else
            # Parse the JSON output to get environment variable IDs
            env_ids=$(echo "$environments" | jq -r '.[].id')

            for env_id in $env_ids; do
              echo "Removing environment variable ID: $env_id"
              # Delete environment variable by ID
              vercel env rm "$env_id" --environment=preview --git-branch="$branch_name" -t $token -y
            done
          fi
