name: Pull Request Closed

on:
  pull_request:
    branches-ignore:
      - "live"
    types:
      - closed

jobs:
  clean_up:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get PR branch name
        id: get_pr_branch_name
        run: |
            branch_name=${GITHUB_REF#refs/heads/}
            echo "branch_name=${branch_name}" >> $GITHUB_OUTPUT
            echo $branch_name

      - name: Search branch by name
        id: get_branch_id
        run: |
          branch_id=$(curl --silent \
            "https://console.neon.tech/api/v2/projects/${{ secrets.NEON_PROJECT_ID }}/branches" \
            --header "Accept: application/json" \
            --header "Content-Type: application/json" \
            --header "Authorization: Bearer ${{ secrets.NEON_API_KEY }}" \
            | jq -r .branches \
            | jq -c '.[] | select(.name | contains("'${{ steps.get_pr_branch_name.outputs.branch_name }}'")) .id' \
            | jq -r \
            ) \
            
          echo "branch_id=${branch_id}" >> $GITHUB_OUTPUT

      - name: Delete Neon Branch
        uses: neondatabase/delete-branch-action@v2
        with:
          project_id: ${{ secrets.NEON_PROJECT_ID }}
          branch_id: ${{ steps.get_branch_id.outputs.branch_id }}
          api_key: ${{ secrets.NEON_API_KEY }}

      - name: Delete Preview Environments
        run: |
          token="${{ secrets.VERCEL_TOKEN }}"
          pull_request_id="${{ steps.get_pull_request_sha.outputs.pull_request_sha }}"
          environments=$(vercel list -m "pullRequestId=$pull_request_id" -t $token -y)
          echo "Environments to delete: $environments"
          for env in $environments; do
            echo "Removing environment: $env"
            vercel remove "$env" -t $token -y
          done
