name: Pull Request Closed

on:
  pull_request:
    branches-ignore:
      - "live"
    types:
      - closed

jobs:
  clean_up:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get PR branch name
        id: get_pr_branch_name
        run: |
          pr_branch_name=$(jq --raw-output .pull_request.head.ref "$GITHUB_EVENT_PATH")
          echo "pr_branch_name=${pr_branch_name}" >> $GITHUB_OUTPUT
          echo $pr_branch_name

      - name: Search branch by name
        id: get_branch_id
        run: |
          branch_id=$(curl --silent \
            "https://console.neon.tech/api/v2/projects/${{ secrets.NEON_PROJECT_ID }}/branches" \
            --header "Accept: application/json" \
            --header "Content-Type: application/json" \
            --header "Authorization: Bearer ${{ secrets.NEON_API_KEY }}" \
            | jq -r .branches \
            | jq -c '.[] | select(.name | contains("'${{ steps.get_pr_branch_name.outputs.pr_branch_name }}'")) .id' \
            | jq -r \
            ) \
            
          echo "branch_id=${branch_id}" >> $GITHUB_OUTPUT

      - name: Delete Neon Branch
        uses: neondatabase/delete-branch-action@v2
        with:
          project_id: ${{ secrets.NEON_PROJECT_ID }}
          branch_id: ${{ steps.get_branch_id.outputs.branch_id }}
          api_key: ${{ secrets.NEON_API_KEY }}

      - name: Delete Preview Environment variables
        run: |
          token="${{ secrets.VERCEL_TOKEN }}"
          branch_name="${{ steps.get_pr_branch_name.outputs.pr_branch_name }}"

          vercel link -t $token -y
          echo "vercel env ls preview $branch_name -t $token -y"
          environments=$(vercel env ls preview $branch_name -t $token -y)
          echo "Environment vars to delete: $environments"
          
          # Parse the JSON output to get environment variable names
          env_names=$(echo "$environments" | jq -r '.[].key')

          for env_name in $env_names; do
            echo "Removing environment variable: $env_name"
            # Delete environment variable by name
            vercel env rm "$env_name" --environment=preview --git-branch="$branch_name" -t $token -y
          done