name: Deploy Main

on:
  push:
    branches:
      - "main"

jobs:
  deploy-main:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get last commit SHA
        id: get_sha
        run: |
          echo sha="${{ github.event.before }}" | cut -c1-8 >> $GITHUB_OUTPUT

      - name: Search branch by name
        id: get_branch_id
        run: |
          branch_id=$(curl --silent \
            "https://console.neon.tech/api/v2/projects/${{ secrets.NEON_PROJECT_ID }}/branches" \
            --header "Accept: application/json" \
            --header "Content-Type: application/json" \
            --header "Authorization: Bearer ${{ secrets.NEON_API_KEY }}" \
            | jq -r .branches \
            | jq -c '.[] | select(.name | contains("'${{ steps.get_sha.outputs.sha }}'")) .id' \
            | jq -r \
            ) \
            
          echo "branch_id=${branch_id}" >> $GITHUB_OUTPUT

      - name: Run Prisma Migrate
        run: |
          cd packages/db
          touch .env
          echo DATABASE_URL="${{ secrets.DATABASE_URL}}" >> .env
          echo DIRECT_DATABASE_URL="${{ secrets.DIRECT_DATABASE_URL}}" >> .env
          npm i -g pnpm
          pnpm i
          pnpm prisma migrate deploy

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        # TODO: change env to preview
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        # TODO: remove prod flag
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Preview to Vercel
        id: deploy
        run: |
          token="${{ secrets.VERCEL_TOKEN }}"
          database_url="${{ secrets.DATABASE_URL}}"
          direct_database_url="${{ secrets.DIRECT_DATABASE_URL}}"
          echo preview_url=$(
            vercel deploy \
              --prebuilt \
              # TODO: remove prod flag
              --prod \
              --env DATABASE_URL=$database_url \
              --env DIRECT_DATABASE_URL=$direct_database_url \
              -t $token
          ) >> $GITHUB_OUTPUT